spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          auth: true
    host: smtp.gmail.com
    username: rathorvijay529@gmail.com
    password: !VijayRathor93
    port: 587
